---
- name: Déployer l'application sur le serveur de production
  hosts: production
  become: true

  tasks:
    - name: Mettre à jour le code source
      git:
        repo: 'https://github.com/1ke4real/Dashcontrol.git'
        dest: '/var/www/Dashcontrol'
        version: 'master'

    - name: Nettoyer les ressources Docker inutilisées
      command: docker system prune -f

    - name: Nettoyer les volumes Docker inutilisés
      command: docker volume prune -f

    - name: Nettoyer les réseaux Docker inutilisés
      command: docker network prune -f
    - name: Vérifier que le fichier docker-compose.yml existe
      stat:
        path: ./docker-compose.yml
        register: docker_compose_file

    - name: Démarrer les conteneurs Docker
      command: docker-compose up --build -d
      args:
        chdir: ./
      when: docker_compose_file.stat.exists

    - name: Installer les dépendances composer
      command: docker compose exec php composer install
      args:
        chdir: ./

