---
- name: Déployer l'application sur le serveur de production
  hosts: production
  become: true

  tasks:
    - name: Mettre à jour le code source
      git:
        repo: 'https://github.com/1ke4real/Dashcontrol.git'
        dest: /var/www/Dashcontrol
        version: master

    - name: Supprimer les conteneurs conflictuels (php)
      shell: |
        if [ $(docker ps -aq -f name=php) ]; then
          docker rm -f php
        fi

    - name: Arrêter et supprimer les conteneurs existants
      command: docker-compose down
      args:
        chdir: /var/www/Dashcontrol

    - name: Nettoyer les ressources Docker inutilisées
      command: docker system prune -f

    - name: Démarrer les conteneurs Docker
      command: docker-compose up --build -d
      args:
        chdir: /var/www/Dashcontrol

    - name: Installer les dépendances composer
      command: docker compose exec php composer install
      args:
        chdir: /var/www/Dashcontrol