---
- name: Déployer l'application sur le serveur de production
  hosts: production
  become: true

  tasks:
    - name: Mettre à jour le code source
      git:
        repo: 'https://github.com/1ke4real/Dashcontrol.git'
        dest: /var/www/Dashcontrol
        version: master

    - name: Nettoyer les ressources Docker inutilisées
      command: make prune
      args:
            chdir: /var/www/Dashcontrol
    - name: Vérifier que le fichier docker-compose.yml existe
      stat:
        path: /var/www/Dashcontrol/docker-compose.yml
      register: docker_compose_file

    - name: Arrêter et supprimer les conteneurs existants
      command: docker-compose down
      args:
        chdir: /var/www/Dashcontrol
      when: docker_compose_file.stat.exists

    - name: Démarrer les conteneurs Docker
      command: docker-compose up --build -d
      args:
        chdir: /var/www/Dashcontrol
      when: docker_compose_file.stat.exists

    - name: Installer les dépendances composer
      command: docker compose exec php composer install
      args:
        chdir: /var/www/Dashcontrol