name: Build, Test and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
      - name: build the docker image
        run: docker-compose up --build -d
  quality:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
      - name: build the docker image
        run: docker-compose up --build -d
      - name: php cs fixer
        run: docker-compose exec php vendor/bin/php-cs-fixer fix --dry-run --using-cache=no --verbose --diff
      - name: phpstan
        run: docker-compose exec php vendor/bin/phpstan analyse src --level=7
      - name: phpinsights
        run: docker-compose exec php vendor/bin/phpinsights
  test-database:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
      - name: build the docker image
        run: docker-compose up --build -d
      - name: database shemat validation
        run: docker-compose exec php bin/console doctrine:schema:validate
